<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ProductSerial extends Model
{
    //
    protected $fillable = [
        'product_id',
        'auto_generated_serial',
        'manual_serial',
        'cost_price',
        'selling_price',
        'discount_price',
        'tax',
        'final_price',
        'main_product_image',
        'additional_product_images',
        'variations',
        'status',
    ];

    protected $casts = [
        'additional_product_images' => 'array',
        'variations' => 'array',
    ];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function ecommerceProduct()
    {
        return $this->belongsTo(EcommerceProduct::class);
    }

    // public static function generateAutoSerial($productId)
    // {
    //     $lastSerial = ProductSerial::where('product_id', $productId)
    //         ->orderBy('id', 'desc')
    //         ->first();

    //     if ($lastSerial) {
    //         $lastSerialNumber = intval(substr($lastSerial->auto_generated_serial, -4));
    //         return 'P' . str_pad($lastSerialNumber + 1, 4, '0', STR_PAD_LEFT);
    //     } else {
    //         return 'P0001';
    //     }
    // }

    public static function generateAutoSerial(string $sku)
    {
        do {
            // 4-character random alphanumeric
            $random = strtoupper(Str::random(4));

            // Build final serial
            $serial = 'PRO-'.$sku.'-'.$random;

            // Ensure uniqueness
            $exists = ProductSerial::where('auto_generated_serial', $serial)->exists();
        } while ($exists);

        return $serial;
    }

    public function getFinalSerialAttribute()
    {
        return $this->manual_serial ?? $this->auto_generated_serial;
    }

    public function getIsManualAttribute()
    {
        return ! is_null($this->manual_serial);
    }

    public function getIsAutoGeneratedAttribute()
    {
        return is_null($this->manual_serial);
    }

    public function getIsSoldAttribute()
    {
        return $this->status == 2;
    }

    public function getIsScrapAttribute()
    {
        return $this->status == 3;
    }

    public function getIsActiveAttribute()
    {
        return $this->status == 1;
    }

    public function getIsInactiveAttribute()
    {
        return $this->status == 0;
    }

    public function getIsPendingAttribute()
    {
        return $this->status == 0;
    }

    public function getIsApprovedAttribute()
    {
        return $this->status == 1;
    }

    public function getIsRejectedAttribute()
    {
        return $this->status == 2;
    }

    public function getIsProcessingAttribute()
    {
        return $this->status == 3;
    }

    public function getIsProcessedAttribute()
    {
        return $this->status == 4;
    }

    public function getIsPickingAttribute()
    {
        return $this->status == 5;
    }

    public function getIsPickedAttribute()
    {
        return $this->status == 6;
    }

    public function getIsCompletedAttribute()
    {
        return $this->status == 7;
    }

    public function getIsCancelledAttribute()
    {
        return $this->status == 8;
    }

    public function getIsOnHoldAttribute()
    {
        return $this->status == 9;
    }

    public function getIsDiagnosisCompletedAttribute()
    {
        return $this->status == 10;
    }

    public function getIsInStockAttribute()
    {
        return $this->status == 1;
    }

    public function getIsOutofStockAttribute()
    {
        return $this->status == 2;
    }

    public function getIsLowStockAttribute()
    {
        return $this->status == 3;
    }

    public function getIsHighStockAttribute()
    {
        return $this->status == 4;
    }
}
